spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

resilience4j:
  circuitBreaker:
    instances:
        orderServiceCircuitBreaker:
            registerHealthIndicator: true
            eventConsumerBufferSize: 10
            slidingWindowSize: 5
            slidingWindowType: COUNT_BASED
            failureRateThreshold: 50
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            waitDurationInOpenState: 5s
            automaticTransitionFromOpenToHalfOpenEnabled: true
